// dashboard/server.rs
//! RUBIX HTTP dashboard server — slow-path only, fully security-hardened.
//!
//! ## Token rotation (non-negotiable)
//!
//! A 32-byte cryptographically random token is generated by `main.rs` using
//! `OsRng` on every engine start.  It is passed into `DashboardServer::new()`
//! as an `Arc<String>` and never touches the filesystem, tracing log, or any
//! persistent store.  It is printed ONCE to the terminal in the startup banner.
//!
//! Consequence: every RUBIX restart invalidates the previous token.  Any
//! browser session from before the restart must re-authenticate.  This is
//! intentional — it means a stolen session cookie is automatically invalidated
//! on the next restart.
//!
//! ## Security controls
//!
//! 1. Token rotation   — new OsRng token on every start, terminal-only display
//! 2. Bearer auth      — every /api/* request requires Authorization: Bearer <token>
//! 3. Constant-time    — token comparison is timing-attack-proof
//! 4. CORS lock        — Access-Control-Allow-Origin = exact bound address only
//! 5. Rate limiting    — 30 POST/min/IP, 120 GET/min/IP, 8192 IP cap
//! 6. Security headers — CSP, X-Frame-Options, nosniff, no-referrer on all responses
//! 7. No token in logs — token never written to tracing, files, or SQLite
//! 8. sessionStorage   — browser stores token in tab-scoped storage only
//! 9. Host default     — 127.0.0.1 loopback; 0.0.0.0 requires explicit config
//!
//! ## Auth boundary
//!
//! GET / serves the HTML shell unconditionally — it contains zero sensitive data
//! and hosts the auth overlay that collects the token from the operator.
//! Enforcing auth on GET / would return a 401 JSON blob to a browser with no
//! token, meaning the page never loads and the overlay never renders.
//! Auth is enforced on every /api/* route without exception.
//!
//! ## Fast-path isolation (unchanged)
//!
//! Runs in its own tokio::spawn task.
//! Reads LiveStats via RwLock::read() only.
//! POST commands route through existing CommandHandler.
//! Zero code in the packet loop.

use crate::control::commands::{Command, CommandResponse};
use crate::control::handler::CommandHandler;
use crate::config::DashboardConfig;
use crate::types::stats::LiveStats;

use axum::{
    body::Body,
    extract::{ConnectInfo, State},
    http::{header, HeaderMap, HeaderValue, Request, StatusCode},
    middleware::{self, Next},
    response::{IntoResponse, Response},
    routing::{get, options, post},
    Json, Router,
};
use dashmap::DashMap;
use parking_lot::RwLock;
use serde::Deserialize;
use std::net::{IpAddr, SocketAddr};
use std::sync::Arc;
use std::time::{Duration, Instant};
use tracing::{error, info, warn};

// ── Rate limiter constants ────────────────────────────────────────────────────

/// Max POST requests (mutating) per IP per window.
const RATE_LIMIT_POST_MAX:  u32      = 30;
/// Max GET requests (read) per IP per window.
const RATE_LIMIT_GET_MAX:   u32      = 120;
/// Sliding window duration.
const RATE_LIMIT_WINDOW:    Duration = Duration::from_secs(60);
/// Lazy eviction interval for stale buckets.
const RATE_EVICT_INTERVAL:  Duration = Duration::from_secs(120);
/// Hard cap on tracked IPs — prevents memory exhaustion under IP spoofing.
const RATE_MAX_TRACKED_IPS: usize    = 8_192;

// ── Rate limiter ──────────────────────────────────────────────────────────────

#[derive(Clone)]
struct RateBucket {
    get_count:  u32,
    post_count: u32,
    window_end: Instant,
}

#[derive(Clone)]
struct RateLimiter {
    map:        Arc<DashMap<IpAddr, RateBucket>>,
    last_evict: Arc<RwLock<Instant>>,
}

impl RateLimiter {
    fn new() -> Self {
        Self {
            map:        Arc::new(DashMap::with_capacity(256)),
            last_evict: Arc::new(RwLock::new(Instant::now())),
        }
    }

    #[inline]
    fn check_get(&self, ip: IpAddr) -> bool {
        self.check_inner(ip, false)
    }

    #[inline]
    fn check_post(&self, ip: IpAddr) -> bool {
        self.check_inner(ip, true)
    }

    fn check_inner(&self, ip: IpAddr, is_post: bool) -> bool {
        let now = Instant::now();

        {
            let last = *self.last_evict.read();
            if now.duration_since(last) >= RATE_EVICT_INTERVAL {
                *self.last_evict.write() = now;
                self.map.retain(|_, b| b.window_end > now);
            }
        }

        if self.map.len() >= RATE_MAX_TRACKED_IPS && !self.map.contains_key(&ip) {
            warn!(%ip, max = RATE_MAX_TRACKED_IPS, "Rate limiter at capacity — denying");
            return false;
        }

        let mut entry = self.map.entry(ip).or_insert_with(|| RateBucket {
            get_count:  0,
            post_count: 0,
            window_end: now + RATE_LIMIT_WINDOW,
        });

        if now >= entry.window_end {
            entry.get_count  = 0;
            entry.post_count = 0;
            entry.window_end = now + RATE_LIMIT_WINDOW;
        }

        if is_post {
            entry.post_count += 1;
            entry.post_count <= RATE_LIMIT_POST_MAX
        } else {
            entry.get_count += 1;
            entry.get_count <= RATE_LIMIT_GET_MAX
        }
    }
}

// ── Shared application state ──────────────────────────────────────────────────

#[derive(Clone)]
struct AppState {
    stats:        Arc<RwLock<LiveStats>>,
    handler:      Arc<CommandHandler>,
    rate_limiter: RateLimiter,
    cors_origin:  Arc<String>,
    token:        Arc<String>,
}

// ── Public server handle ──────────────────────────────────────────────────────

pub struct DashboardStartResult {
    pub addr: SocketAddr,
    pub host: String,
}

pub struct DashboardServer {
    config:  DashboardConfig,
    stats:   Arc<RwLock<LiveStats>>,
    handler: Arc<CommandHandler>,
    token:   Arc<String>,
}

impl DashboardServer {
    pub fn new(
        config:  DashboardConfig,
        stats:   Arc<RwLock<LiveStats>>,
        handler: Arc<CommandHandler>,
        token:   Arc<String>,
    ) -> Self {
        Self { config, stats, handler, token }
    }

    pub async fn start(self) -> Option<DashboardStartResult> {
        if !self.config.enabled {
            info!("Dashboard disabled in config — skipping");
            return None;
        }

        let host: IpAddr = self.config.host.parse().unwrap_or_else(|e| {
            warn!(raw = %self.config.host, error = %e,
                "Invalid dashboard.host — falling back to 127.0.0.1");
            "127.0.0.1".parse().unwrap()
        });

        if host.is_unspecified() {
            warn!(
                "Dashboard bound to 0.0.0.0 — reachable from ALL network interfaces. \
                 The session token is still required for every request."
            );
        }

        let addr     = SocketAddr::new(host, self.config.port);
        let listener = match tokio::net::TcpListener::bind(addr).await {
            Ok(l)  => l,
            Err(e) => {
                error!(addr = %addr, error = %e,
                    "Dashboard failed to bind — running without dashboard");
                return None;
            }
        };

        let bound = listener.local_addr().ok()?;

        let display_host = if bound.ip().is_unspecified() {
            "127.0.0.1".to_string()
        } else {
            bound.ip().to_string()
        };

        let cors_origin = Arc::new(
            format!("http://{}:{}", display_host, bound.port())
        );

        info!("Dashboard server starting (token authentication active)");

        let state = AppState {
            stats:        self.stats,
            handler:      self.handler,
            rate_limiter: RateLimiter::new(),
            cors_origin,
            token:        self.token,
        };

        let app = build_router(state);

        tokio::spawn(async move {
            if let Err(e) = axum::serve(
                listener,
                app.into_make_service_with_connect_info::<SocketAddr>(),
            ).await {
                error!(error = %e, "Dashboard server exited with error");
            }
        });

        info!(addr = %bound, "Dashboard server listening");
        Some(DashboardStartResult { addr: bound, host: display_host })
    }
}

// ── Token generation ──────────────────────────────────────────────────────────

pub fn generate_dashboard_token() -> Arc<String> {
    use std::fmt::Write as FmtWrite;
    let mut bytes = [0u8; 32];
    getrandom::getrandom(&mut bytes)
        .expect("OsRng failed — system entropy source unavailable");
    let mut token = String::with_capacity(64);
    for byte in &bytes {
        write!(token, "{:02x}", byte).expect("fmt::Write on String is infallible");
    }
    Arc::new(token)
}

// ── Router ────────────────────────────────────────────────────────────────────

fn build_router(state: AppState) -> Router {
    Router::new()
        .route("/",              get(serve_index))
        .route("/api/stats",     options(handle_preflight))
        .route("/api/block",     options(handle_preflight))
        .route("/api/unblock",   options(handle_preflight))
        .route("/api/block_pid", options(handle_preflight))
        .route("/api/stats",     get(api_stats))
        .route("/api/status",    get(api_status))
        .route("/api/rules",     get(api_rules))
        .route("/api/block",     post(api_block))
        .route("/api/unblock",   post(api_unblock))
        .route("/api/block_pid", post(api_block_pid))
        .layer(middleware::from_fn_with_state(state.clone(), security_headers_middleware))
        .with_state(state)
}

// ── Security headers middleware ───────────────────────────────────────────────

async fn security_headers_middleware(
    State(s): State<AppState>,
    req:      Request<Body>,
    next:     Next,
) -> Response {
    let mut response = next.run(req).await;
    let h = response.headers_mut();

    h.insert(header::ACCESS_CONTROL_ALLOW_ORIGIN,
        HeaderValue::from_str(&s.cors_origin)
            .unwrap_or(HeaderValue::from_static("null")));
    h.insert(header::ACCESS_CONTROL_ALLOW_METHODS,
        HeaderValue::from_static("GET, POST, OPTIONS"));
    h.insert(header::ACCESS_CONTROL_ALLOW_HEADERS,
        HeaderValue::from_static("Content-Type, Authorization"));
    h.insert(header::ACCESS_CONTROL_MAX_AGE,
        HeaderValue::from_static("3600"));
    h.insert("X-Content-Type-Options",
        HeaderValue::from_static("nosniff"));
    h.insert("X-Frame-Options",
        HeaderValue::from_static("DENY"));
    h.insert("X-XSS-Protection",
        HeaderValue::from_static("1; mode=block"));
    h.insert("Referrer-Policy",
        HeaderValue::from_static("no-referrer"));
    h.insert(header::CONTENT_SECURITY_POLICY,
        HeaderValue::from_static(
            "default-src 'self'; \
             script-src 'unsafe-inline'; \
             style-src 'unsafe-inline'; \
             connect-src 'self'; \
             img-src 'none'; \
             object-src 'none'; \
             frame-ancestors 'none'"
        ));

    response
}

// ── CORS preflight ────────────────────────────────────────────────────────────

async fn handle_preflight() -> impl IntoResponse {
    StatusCode::NO_CONTENT
}

// ── Auth ──────────────────────────────────────────────────────────────────────

#[inline]
fn check_auth(headers: &HeaderMap, token: &Arc<String>) -> Result<(), Response> {
    let provided = headers
        .get(header::AUTHORIZATION)
        .and_then(|v| v.to_str().ok())
        .and_then(|v| v.strip_prefix("Bearer "))
        .unwrap_or("");

    if constant_time_eq(provided.as_bytes(), token.as_bytes()) {
        Ok(())
    } else {
        Err((
            StatusCode::UNAUTHORIZED,
            [(header::WWW_AUTHENTICATE, "Bearer realm=\"RUBIX\"")],
            Json(serde_json::json!({ "success": false, "message": "Unauthorized" })),
        ).into_response())
    }
}

#[inline(always)]
fn constant_time_eq(a: &[u8], b: &[u8]) -> bool {
    if a.len() != b.len() {
        let mut sink: u8 = 0;
        for byte in a { sink |= byte ^ byte; }
        let _ = sink;
        return false;
    }
    let mut diff: u8 = 0;
    for (x, y) in a.iter().zip(b.iter()) { diff |= x ^ y; }
    diff == 0
}

// ── Rate limit / auth error responses ────────────────────────────────────────

fn rate_err() -> Response {
    (
        StatusCode::TOO_MANY_REQUESTS,
        Json(serde_json::json!({ "success": false, "message": "Too many requests — slow down" })),
    ).into_response()
}

fn auth_err_response() -> Response {
    (
        StatusCode::UNAUTHORIZED,
        [(header::WWW_AUTHENTICATE, "Bearer realm=\"RUBIX\"")],
        Json(serde_json::json!({ "success": false, "message": "Unauthorized" })),
    ).into_response()
}

// ── GET / — HTML shell, no auth ───────────────────────────────────────────────

async fn serve_index() -> Response {
    Response::builder()
        .status(StatusCode::OK)
        .header(header::CONTENT_TYPE, "text/html; charset=utf-8")
        .header(header::CACHE_CONTROL, "no-store")
        .body(Body::from(DASHBOARD_HTML))
        .unwrap()
}

// ── GET /api/stats ────────────────────────────────────────────────────────────

async fn api_stats(
    State(s):          State<AppState>,
    ConnectInfo(peer): ConnectInfo<SocketAddr>,
    headers:           HeaderMap,
) -> Response {
    if check_auth(&headers, &s.token).is_err() { return auth_err_response(); }
    if !s.rate_limiter.check_get(peer.ip())    { return rate_err(); }
    let snapshot: LiveStats = s.stats.read().clone();
    ([(header::CACHE_CONTROL, "no-store")], Json(snapshot)).into_response()
}

// ── GET /api/status ───────────────────────────────────────────────────────────

async fn api_status(
    State(s):          State<AppState>,
    ConnectInfo(peer): ConnectInfo<SocketAddr>,
    headers:           HeaderMap,
) -> Response {
    if check_auth(&headers, &s.token).is_err() { return auth_err_response(); }
    if !s.rate_limiter.check_get(peer.ip())    { return rate_err(); }
    let resp: CommandResponse = s.handler.handle(Command::Status).await;
    ([(header::CACHE_CONTROL, "no-store")], Json(resp)).into_response()
}

// ── GET /api/rules ────────────────────────────────────────────────────────────

async fn api_rules(
    State(s):          State<AppState>,
    ConnectInfo(peer): ConnectInfo<SocketAddr>,
    headers:           HeaderMap,
) -> Response {
    if check_auth(&headers, &s.token).is_err() { return auth_err_response(); }
    if !s.rate_limiter.check_get(peer.ip())    { return rate_err(); }
    let resp: CommandResponse = s.handler.handle(Command::GetRules).await;
    ([(header::CACHE_CONTROL, "no-store")], Json(resp)).into_response()
}

// ── POST /api/block ───────────────────────────────────────────────────────────

#[derive(Deserialize)]
struct BlockIpRequest {
    ip:            std::net::IpAddr,
    duration_secs: Option<u64>,
    reason:        Option<String>,
}

async fn api_block(
    State(s):          State<AppState>,
    ConnectInfo(peer): ConnectInfo<SocketAddr>,
    headers:           HeaderMap,
    Json(body):        Json<BlockIpRequest>,
) -> Response {
    if check_auth(&headers, &s.token).is_err() { return auth_err_response(); }
    if !s.rate_limiter.check_post(peer.ip())   { return rate_err(); }
    let resp = s.handler.handle(Command::BlockIp {
        ip:            body.ip,
        duration_secs: body.duration_secs,
        reason:        body.reason,
    }).await;
    ([(header::CACHE_CONTROL, "no-store")], Json(resp)).into_response()
}

// ── POST /api/unblock ─────────────────────────────────────────────────────────

#[derive(Deserialize)]
struct UnblockIpRequest {
    ip: std::net::IpAddr,
}

async fn api_unblock(
    State(s):          State<AppState>,
    ConnectInfo(peer): ConnectInfo<SocketAddr>,
    headers:           HeaderMap,
    Json(body):        Json<UnblockIpRequest>,
) -> Response {
    if check_auth(&headers, &s.token).is_err() { return auth_err_response(); }
    if !s.rate_limiter.check_post(peer.ip())   { return rate_err(); }
    let resp = s.handler.handle(Command::UnblockIp { ip: body.ip }).await;
    ([(header::CACHE_CONTROL, "no-store")], Json(resp)).into_response()
}

// ── POST /api/block_pid ───────────────────────────────────────────────────────

#[derive(Deserialize)]
struct BlockPidRequest {
    pid:           u32,
    duration_secs: Option<u64>,
    reason:        Option<String>,
}

async fn api_block_pid(
    State(s):          State<AppState>,
    ConnectInfo(peer): ConnectInfo<SocketAddr>,
    headers:           HeaderMap,
    Json(body):        Json<BlockPidRequest>,
) -> Response {
    if check_auth(&headers, &s.token).is_err() { return auth_err_response(); }
    if !s.rate_limiter.check_post(peer.ip())   { return rate_err(); }
    let resp = s.handler.handle(Command::BlockPid {
        pid:           body.pid,
        duration_secs: body.duration_secs,
        reason:        body.reason,
    }).await;
    ([(header::CACHE_CONTROL, "no-store")], Json(resp)).into_response()
}

// ── Embedded dashboard HTML ───────────────────────────────────────────────────

const DASHBOARD_HTML: &str = r#"<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>RUBIX — Network Defence Dashboard</title>
<style>
  :root {
    --bg:      #0a0e1a;
    --panel:   #0f1626;
    --border:  #1e2d4a;
    --cyan:    #00d4ff;
    --green:   #00ff88;
    --red:     #ff3355;
    --yellow:  #ffcc00;
    --magenta: #cc44ff;
    --text:    #c8d8f0;
    --dim:     #5a7090;
    --font:    'Courier New', Courier, monospace;
  }
  * { box-sizing: border-box; margin: 0; padding: 0; }
  body { background: var(--bg); color: var(--text); font-family: var(--font); font-size: 13px; min-height: 100vh; }

  /* ── Auth overlay ── */
  #auth-overlay {
    display: none; position: fixed; inset: 0;
    background: rgba(0,0,0,0.92); z-index: 9999;
    align-items: center; justify-content: center;
  }
  #auth-overlay.visible { display: flex; }
  #auth-box {
    background: var(--panel); border: 1px solid var(--cyan);
    border-radius: 6px; padding: 36px; width: 380px; text-align: center;
  }
  #auth-box h2 { color: var(--cyan); letter-spacing: 4px; margin-bottom: 8px; font-size: 20px; }
  #auth-subtitle { color: var(--dim); font-size: 11px; margin-bottom: 20px; letter-spacing: 1px; }
  #auth-box input {
    width: 100%; padding: 10px; margin-bottom: 12px;
    background: #0a0e1a; border: 1px solid var(--border);
    color: var(--text); font-family: var(--font); font-size: 13px;
    border-radius: 3px; outline: none; letter-spacing: 1px;
  }
  #auth-box input:focus { border-color: var(--cyan); }
  #auth-submit {
    width: 100%; padding: 11px; background: var(--cyan); color: #000;
    border: none; border-radius: 3px; font-family: var(--font);
    font-size: 13px; font-weight: bold; cursor: pointer; letter-spacing: 2px;
  }
  #auth-submit:hover { opacity: 0.85; }
  #auth-error { color: var(--red); font-size: 11px; margin-top: 10px; min-height: 16px; }
  #auth-hint  { color: var(--dim); font-size: 10px; margin-top: 14px; line-height: 1.6; }

  /* ── Header ── */
  header {
    background: var(--panel); border-bottom: 1px solid var(--border);
    padding: 12px 24px; display: flex; align-items: center; justify-content: space-between;
  }
  .logo { color: var(--cyan); font-size: 20px; font-weight: bold; letter-spacing: 4px; }
  .logo span { color: var(--magenta); }
  .status-dot {
    width: 10px; height: 10px; border-radius: 50%; background: var(--green);
    display: inline-block; margin-right: 6px; animation: pulse 2s infinite;
  }
  @keyframes pulse { 0%,100%{opacity:1} 50%{opacity:.3} }
  .header-right { display: flex; align-items: center; gap: 16px; color: var(--dim); font-size: 12px; }

  /* ── Layout ── */
  main { padding: 20px 24px; display: grid; grid-template-columns: repeat(4,1fr); gap: 16px; }

  /* ── Panels ── */
  .panel { background: var(--panel); border: 1px solid var(--border); border-radius: 4px; padding: 14px 16px; }
  .panel-title { color: var(--cyan); font-size: 11px; letter-spacing: 2px; text-transform: uppercase; margin-bottom: 12px; border-bottom: 1px solid var(--border); padding-bottom: 8px; }

  /* ── Stat cards ── */
  .stat-card { grid-column: span 1; text-align: center; }
  .stat-value { font-size: 32px; font-weight: bold; line-height: 1.1; margin-bottom: 4px; }
  .stat-sub   { color: var(--dim); font-size: 11px; margin-top: 4px; }
  .color-cyan    { color: var(--cyan); }
  .color-red     { color: var(--red); }
  .color-yellow  { color: var(--yellow); }
  .color-green   { color: var(--green); }

  /* ── Heartbeat ── */
  .heartbeat-panel { grid-column: span 4; }
  #heartbeat { color: var(--green); font-size: 16px; letter-spacing: 2px; word-break: break-all; }

  /* ── Process table ── */
  .proc-panel { grid-column: span 3; }
  table { width: 100%; border-collapse: collapse; }
  th { color: var(--dim); font-size: 11px; text-align: left; padding: 4px 8px; border-bottom: 1px solid var(--border); }
  td { padding: 5px 8px; border-bottom: 1px solid #131c2e; white-space: nowrap; }
  tr:last-child td { border-bottom: none; }
  tr:hover td { background: #12192a; }

  /* ── Block control ── */
  .block-panel { grid-column: span 1; }
  .input-row { display: flex; flex-direction: column; gap: 8px; margin-bottom: 12px; }
  input[type="text"], input[type="number"] {
    background: #0a0e1a; border: 1px solid var(--border);
    color: var(--text); font-family: var(--font); font-size: 13px;
    padding: 7px 10px; border-radius: 3px; width: 100%; outline: none;
  }
  input[type="text"]:focus, input[type="number"]:focus { border-color: var(--cyan); }
  .btn { width: 100%; padding: 8px; border: none; border-radius: 3px; font-family: var(--font); font-size: 13px; cursor: pointer; letter-spacing: 1px; }
  .btn:hover { opacity: 0.85; }
  .btn-block   { background: var(--red);   color: #000; }
  .btn-unblock { background: var(--green); color: #000; margin-top: 6px; }
  #block-result { margin-top: 10px; font-size: 12px; min-height: 20px; word-break: break-all; }

  /* ── Log ring ── */
  .log-panel { grid-column: span 4; }
  .log-ring { height: 220px; overflow-y: auto; font-size: 12px; line-height: 1.6; }
  .log-ring::-webkit-scrollbar { width: 6px; }
  .log-ring::-webkit-scrollbar-track { background: #0a0e1a; }
  .log-ring::-webkit-scrollbar-thumb { background: var(--border); border-radius: 3px; }
  .log-entry {
    display: grid;
    grid-template-columns: 90px 60px 120px 120px 60px 60px 60px 120px 1fr;
    gap: 0 8px; padding: 2px 4px; border-bottom: 1px solid #0d1220;
  }
  .log-entry:hover { background: #12192a; }
  .lv-block  { color: var(--red); }
  .lv-alert  { color: var(--yellow); }
  .lv-threat { color: var(--magenta); }
  .lv-normal { color: var(--dim); }
  .lv-error  { color: var(--red); opacity:.7; }
  .col-dim   { color: var(--dim); }

  /* ── Threat feed ── */
  .threat-panel { grid-column: span 4; }
  .threat-ring  { height: 120px; overflow-y: auto; font-size: 12px; }
  .threat-line  { padding: 3px 4px; border-bottom: 1px solid #0d1220; color: var(--magenta); }

  /* ── Responsive ── */
  @media (max-width: 1024px) {
    main { grid-template-columns: repeat(2,1fr); }
    .heartbeat-panel,.log-panel,.threat-panel,.proc-panel,.block-panel { grid-column: span 2; }
  }
  @media (max-width: 600px) {
    main { grid-template-columns: 1fr; padding: 10px; }
    .stat-card,.heartbeat-panel,.proc-panel,.block-panel,.log-panel,.threat-panel { grid-column: span 1; }
  }
</style>
</head>
<body>

<!-- Auth overlay -->
<div id="auth-overlay">
  <div id="auth-box">
    <h2>RUBIX SENTINEL</h2>
    <div id="auth-subtitle">AUTHENTICATION REQUIRED</div>
    <input type="password" id="token-input" placeholder="Paste session token from terminal" autocomplete="off" spellcheck="false">
    <button id="auth-submit" onclick="submitToken()">AUTHENTICATE</button>
    <div id="auth-error"></div>
    <div id="auth-hint">
      Token is printed once in the RUBIX startup banner.<br>
      It rotates on every engine restart.
    </div>
  </div>
</div>

<header>
  <div class="logo">RUB<span>IX</span> <span style="font-size:12px;color:var(--dim)">SENTINEL SOC</span></div>
  <div class="header-right">
    <span><span class="status-dot"></span>ENGINE ONLINE</span>
    <span id="last-update">—</span>
  </div>
</header>

<main>
  <div class="panel stat-card">
    <div class="panel-title">Packets</div>
    <div class="stat-value color-cyan" id="s-packets">—</div>
    <div class="stat-sub"><span id="s-pps">—</span> pps</div>
  </div>
  <div class="panel stat-card">
    <div class="panel-title">Blocked</div>
    <div class="stat-value color-red" id="s-blocked">—</div>
    <div class="stat-sub">total block events</div>
  </div>
  <div class="panel stat-card">
    <div class="panel-title">Alerts</div>
    <div class="stat-value color-yellow" id="s-alerts">—</div>
    <div class="stat-sub">total alert events</div>
  </div>
  <div class="panel stat-card">
    <div class="panel-title">Throughput</div>
    <div class="stat-value color-green" id="s-avgpps">—</div>
    <div class="stat-sub">avg pps · <span id="s-runtime">—</span>s up</div>
  </div>

  <div class="panel heartbeat-panel">
    <div class="panel-title">Packet Rate — Heartbeat</div>
    <div id="heartbeat">loading...</div>
  </div>

  <div class="panel proc-panel">
    <div class="panel-title">Top Processes (5-second window)</div>
    <table>
      <thead><tr>
        <th>PID</th><th>Process</th><th>Packets</th><th>Bytes</th>
        <th>Blocked</th><th>Alerted</th><th>Unique DST</th><th>Protocols</th>
      </tr></thead>
      <tbody id="proc-tbody"></tbody>
    </table>
  </div>

  <div class="panel block-panel">
    <div class="panel-title">Block / Unblock IP</div>
    <div class="input-row">
      <input type="text"   id="ip-input"  placeholder="IP address (e.g. 1.2.3.4)">
      <input type="number" id="dur-input" placeholder="Duration secs (blank = permanent)" min="1">
    </div>
    <button class="btn btn-block"   onclick="doBlock()">BLOCK IP</button>
    <button class="btn btn-unblock" onclick="doUnblock()">UNBLOCK IP</button>
    <div id="block-result"></div>
  </div>

  <div class="panel log-panel">
    <div class="panel-title">Security Event Log (Block · Alert · Threat)</div>
    <div class="log-ring" id="log-ring">
      <div class="col-dim" style="padding:8px 4px">Waiting for events...</div>
    </div>
  </div>

  <div class="panel threat-panel">
    <div class="panel-title">Threat Intelligence Feed</div>
    <div class="threat-ring" id="threat-ring">
      <div class="col-dim" style="padding:8px 4px">No threats detected yet.</div>
    </div>
  </div>
</main>

<script>
"use strict";

// ── Token management ──────────────────────────────────────────────────────────

let _token = sessionStorage.getItem("rubix_tok") || "";

function getAuthHeader() {
  return _token ? { "Authorization": "Bearer " + _token } : {};
}
function clearToken() {
  _token = "";
  sessionStorage.removeItem("rubix_tok");
}
function saveToken(t) {
  _token = t;
  sessionStorage.setItem("rubix_tok", t);
}

// ── Auth overlay ──────────────────────────────────────────────────────────────

function showAuth(msg) {
  document.getElementById("auth-overlay").classList.add("visible");
  document.getElementById("auth-error").textContent = msg || "";
  document.getElementById("token-input").value = "";
  document.getElementById("token-input").focus();
}
function hideAuth() {
  document.getElementById("auth-overlay").classList.remove("visible");
}

async function submitToken() {
  const input = document.getElementById("token-input").value.trim();
  const err   = document.getElementById("auth-error");
  if (!input)                { err.textContent = "Token cannot be empty.";          return; }
  if (input.length !== 64)   { err.textContent = "Token must be 64 hex characters."; return; }
  if (!/^[0-9a-f]+$/.test(input)) { err.textContent = "Token must be lowercase hex."; return; }
  err.textContent = "Verifying...";
  try {
    const r = await fetch("/api/status", {
      headers: { "Authorization": "Bearer " + input }
    });
    if (r.status === 401) { err.textContent = "Invalid token — check the startup banner."; clearToken(); return; }
    if (r.ok) { saveToken(input); hideAuth(); startPolling(); return; }
    err.textContent = "Server error (" + r.status + ") — try again.";
  } catch (e) {
    err.textContent = "Connection failed — is RUBIX running?";
  }
}

document.getElementById("token-input").addEventListener("keydown", e => {
  if (e.key === "Enter") submitToken();
});

// ── Formatting ────────────────────────────────────────────────────────────────

function fmt(n) {
  if (n == null) return "—";
  if (n >= 1e9) return (n/1e9).toFixed(2)+"B";
  if (n >= 1e6) return (n/1e6).toFixed(2)+"M";
  if (n >= 1e3) return (n/1e3).toFixed(1)+"K";
  return String(n);
}
function fmtBytes(b) {
  if (b == null) return "—";
  if (b >= 1073741824) return (b/1073741824).toFixed(2)+" GB";
  if (b >= 1048576)    return (b/1048576).toFixed(2)+" MB";
  if (b >= 1024)       return (b/1024).toFixed(1)+" KB";
  return b+" B";
}
function lvClass(lv) {
  return {block:"lv-block",alert:"lv-alert",threat:"lv-threat",normal:"lv-normal",error:"lv-error"}[lv]||"";
}
function esc(s) {
  return String(s||"").replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;");
}

// ── Process table — stable in-place update (no flicker) ──────────────────────
//
// Problem: replacing tbody.innerHTML every second destroys and recreates every
// DOM node.  The browser repaints each cell individually as it is inserted,
// producing a visible left-to-right wipe that looks like flickering.
//
// Fix: keep a keyed map of existing <tr> elements by PID.
//   • rows that are still present → update only the cells whose text changed
//   • new PIDs                    → create a fresh <tr> and append it
//   • PIDs that disappeared       → remove their <tr>
//   • row order                   → enforced by re-inserting rows in rank order
//     using insertBefore, which moves existing nodes without recreation.
//
// Result: zero DOM destruction on steady-state updates.  Only changed numbers
// are written.  No repaint of stable cells.  No flicker.

// pid → <tr> element
const _procRows = new Map();

function _setCell(td, text, className) {
  // Only touch the DOM if the value actually changed.
  if (td.textContent !== text) td.textContent = text;
  if (className !== undefined && td.className !== className) td.className = className;
}

function renderProcTable(procs) {
  const tbody = document.getElementById("proc-tbody");

  if (!procs || procs.length === 0) {
    // Clear everything and show placeholder.
    _procRows.forEach((tr) => tbody.removeChild(tr));
    _procRows.clear();
    if (!tbody.querySelector(".proc-placeholder")) {
      const tr = document.createElement("tr");
      tr.className = "proc-placeholder";
      tr.innerHTML = '<td colspan="8" class="col-dim" style="padding:12px 8px">No process data yet.</td>';
      tbody.appendChild(tr);
    }
    return;
  }

  // Remove placeholder if present.
  const ph = tbody.querySelector(".proc-placeholder");
  if (ph) tbody.removeChild(ph);

  // Build set of incoming PIDs so we can detect removals.
  const incomingPids = new Set(procs.map(p => p.pid));

  // Remove rows for PIDs that are no longer in the top list.
  _procRows.forEach((tr, pid) => {
    if (!incomingPids.has(pid)) {
      tbody.removeChild(tr);
      _procRows.delete(pid);
    }
  });

  // Update or create rows, then enforce rank order with insertBefore.
  procs.forEach((p, rank) => {
    let tr = _procRows.get(p.pid);

    if (!tr) {
      // New PID — create the row with 8 empty cells.
      tr = document.createElement("tr");
      for (let i = 0; i < 8; i++) tr.appendChild(document.createElement("td"));
      _procRows.set(p.pid, tr);
    }

    // Update each cell only if its content changed — zero DOM writes on steady state.
    const cells = tr.cells;
    _setCell(cells[0], String(p.pid),       "col-dim");
    _setCell(cells[1], esc(p.name),          "");
    _setCell(cells[2], fmt(p.packets),       "color-cyan");
    _setCell(cells[3], fmtBytes(p.bytes),    "col-dim");
    _setCell(cells[4], fmt(p.blocked),       p.blocked  > 0 ? "color-red"    : "col-dim");
    _setCell(cells[5], fmt(p.alerted),       p.alerted  > 0 ? "color-yellow" : "col-dim");
    _setCell(cells[6], String(p.unique_dsts),"col-dim");
    _setCell(cells[7], String(p.protocol_cnt),"col-dim");

    // Enforce rank order: move the row to position `rank` if it is not already there.
    // insertBefore on an already-positioned node is a no-op in most engines,
    // but the explicit check avoids the call entirely on steady state.
    const refNode = tbody.children[rank] || null;
    if (refNode !== tr) {
      tbody.insertBefore(tr, refNode);
    }
  });
}

// ── Render ────────────────────────────────────────────────────────────────────

const $ = id => document.getElementById(id);

function renderStats(d) {
  $("s-packets").textContent = fmt(d.packet_count);
  $("s-blocked").textContent = fmt(d.block_count);
  $("s-alerts").textContent  = fmt(d.alert_count);
  $("s-avgpps").textContent  = d.avg_pps     != null ? d.avg_pps.toFixed(0)     : "—";
  $("s-pps").textContent     = d.pps         != null ? d.pps.toFixed(0)         : "—";
  $("s-runtime").textContent = d.runtime_secs != null ? d.runtime_secs.toFixed(0) : "—";
  $("heartbeat").textContent = d.heartbeat || "_".repeat(30);

  // ── Process table — stable, no flicker ───────────────────────────────────
  renderProcTable(d.top_procs || []);

  // ── Log ring ──────────────────────────────────────────────────────────────
  const logs  = d.recent_logs || [];
  const ring  = $("log-ring");
  const pinned = ring.scrollTop + ring.clientHeight >= ring.scrollHeight - 4;
  ring.innerHTML = logs.length === 0
    ? '<div class="col-dim" style="padding:8px 4px">No security events yet.</div>'
    : [...logs].reverse().map(e => `<div class="log-entry">
        <span class="col-dim">${esc(e.time)}</span>
        <span class="${lvClass(e.level)}">${esc((e.level||"").toUpperCase())}</span>
        <span>${esc(e.src_ip)}</span><span>${esc(e.dst_ip)}</span>
        <span class="col-dim">${e.src_port||0}</span>
        <span class="col-dim">${e.dst_port||0}</span>
        <span class="col-dim">${esc(e.proto)}</span>
        <span class="color-cyan">${esc(e.process)}</span>
        <span class="col-dim">${esc(e.detail)}</span>
      </div>`).join("");
  if (pinned) ring.scrollTop = ring.scrollHeight;

  // ── Threat feed ───────────────────────────────────────────────────────────
  const threats = d.recent_threats || [];
  $("threat-ring").innerHTML = threats.length === 0
    ? '<div class="col-dim" style="padding:8px 4px">No threats detected yet.</div>'
    : [...threats].reverse().map(t => `<div class="threat-line">${esc(t)}</div>`).join("");

  $("last-update").textContent = "Updated " + new Date().toLocaleTimeString();
}

// ── Poll ──────────────────────────────────────────────────────────────────────

let _pollTimer = null;

async function poll() {
  try {
    const r = await fetch("/api/stats", { headers: getAuthHeader() });
    if (r.status === 401) {
      clearToken();
      showAuth("Session expired — RUBIX may have restarted. Enter the new token.");
      stopPolling();
      return;
    }
    if (r.ok) renderStats(await r.json());
  } catch (_) {
    $("last-update").textContent = "Connection lost — retrying...";
  }
}

function startPolling() {
  if (_pollTimer) return;
  poll();
  _pollTimer = setInterval(poll, 1000);
}
function stopPolling() {
  if (_pollTimer) { clearInterval(_pollTimer); _pollTimer = null; }
}

// ── Boot ──────────────────────────────────────────────────────────────────────

if (_token) {
  startPolling();
} else {
  showAuth();
}

// ── Block / Unblock ───────────────────────────────────────────────────────────

async function apiPost(url, body) {
  const r = await fetch(url, {
    method: "POST",
    headers: { "Content-Type": "application/json", ...getAuthHeader() },
    body: JSON.stringify(body),
  });
  if (r.status === 401) { clearToken(); showAuth("Session expired."); stopPolling(); return null; }
  if (r.status === 429) return { success: false, message: "Rate limited — slow down." };
  return r.json();
}

async function doBlock() {
  const ip  = $("ip-input").value.trim();
  const dur = $("dur-input").value.trim();
  const res = $("block-result");
  if (!ip) { res.innerHTML = '<span class="color-yellow">Enter an IP address.</span>'; return; }
  const body = { ip };
  if (dur) body.duration_secs = parseInt(dur, 10);
  try {
    const d = await apiPost("/api/block", body);
    if (!d) return;
    res.innerHTML = d.success
      ? `<span class="color-green">[OK] ${esc(d.message)}</span>`
      : `<span class="color-red">[!] ${esc(d.message)}</span>`;
  } catch (e) {
    res.innerHTML = `<span class="color-red">[!] ${esc(String(e))}</span>`;
  }
}

async function doUnblock() {
  const ip  = $("ip-input").value.trim();
  const res = $("block-result");
  if (!ip) { res.innerHTML = '<span class="color-yellow">Enter an IP address.</span>'; return; }
  try {
    const d = await apiPost("/api/unblock", { ip });
    if (!d) return;
    res.innerHTML = d.success
      ? `<span class="color-green">[OK] ${esc(d.message)}</span>`
      : `<span class="color-red">[!] ${esc(d.message)}</span>`;
  } catch (e) {
    res.innerHTML = `<span class="color-red">[!] ${esc(String(e))}</span>`;
  }
}
</script>
</body>
</html>"#;